### ISSUE TITLE
Communication Management Plan

### ISSUE THREAD

**Issue by katanallama** [teamcrusher/threewide#6]
Let's figure out a Comms management plan

|  **COMMUNICATION MANAGEMENT PLAN**                                      |                   |                               |                                               |
|---------------------------------------|-------------------|-------------------------------|-----------------------------------------------| 
|     |                   |                               |                                               |
| **Project Name**                      | Threewide         |                               |                                               |
| **Communication Name**                | **Description**   | **Audience/Attendees**        | **Timing**                                    |
| \[Short name of the communication\]   |                   |                               | \[Date or frequency of the communication\]    |
|                                       |                   |                               |                                               |

**Comment by dav1dk1m** [comment]
Team Standup | Review what each member did and discuss the future event  | Team members | Daily

**Comment by Daniil-Aleshechkin** [comment]
I think our standups should be done via disc but I like that idea
