### ISSUE TITLE
Add a clustered index on userId or gameId for UserGameResultModel and one on strategyId for GameDescriptionModel

### ISSUE THREAD

**Issue by katanallama** [teamcrusher/threewide#91]

**Comment by Daniil-Aleshechkin** [comment]
The only way to do this is to add a collection on the prod db, so I'm just going to do it while deploying the mongo database

**Comment by Daniil-Aleshechkin** [comment]
Apparently you can only deploy mongo 5.0.0 on atlas and clustered indexes are only on 5.3. Not sure how to update the version on there, so I just created regular indexes. Makes inserts slightly slower, but it should be fine and virtually non noticeable for now
